### ISSUE TITLE
Collect respective libraries & Test Peripherals

### ISSUE THREAD

**Issue by aitesam961** [aitesam961/Cattle-Health-Monitoring-WSN#4]
Gather all the libraries and implementation resources for peripherals

**Comment by aitesam961** [comment]
Gathered a Whole bunch of Required libraries but they appeared to me more Generalized and Over-complicated. Looking for something more lightweight and Focused to simplicity

**Comment by Fasihshah** [comment]
We must completed this tast till December 15

**Comment by aitesam961** [comment]
DHT11 Library Collected and Simplified for our use.
DHT11 sensor is tested in depth and all information is collected.
See commit for more

**Comment by aitesam961** [comment]
Issue #5 Test Peripherals Merged into This issue.

**Comment by aitesam961** [comment]
**### DHT11 Test Log**
- Testing Voltage : 3.3V //Cuz the IO voltage
- Sampling rate : 2Hz  //Delay of 2s
- Current Consumption per Transaction : 2.53mA
- Sleep Current: xuA
